"""initial migration

Revision ID: 24c4c537ceb
Revises: d51d4fd475
Create Date: 2015-10-17 23:05:17.296875

"""

# revision identifiers, used by Alembic.
revision = '24c4c537ceb'
down_revision = 'd51d4fd475'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
